### ISSUE TITLE
Would be nice if you supported just computing computing a checksum

### ISSUE THREAD

**Issue by dalewking** [EdoGimo/node-red-contrib-checksum#1]
In my case I just want to compute a checksum, not verify it against an expected one

**Comment by EdoGimo** [comment]
Hi @dalewking, I pushed an update. Now you can simply get the computed checksum from "msg.calcChecksum". I didn't want to change radically the functioning, so it is still required to give a checksum string to be compared with the computed one, but "msg.calcChecksum" is returned regardless so you can just write something random. Let me know if everything works correctly (I added a GitHub Actions test since I'm not able to test it personally atm)!
